/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanPham;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS FX504
 */
public class QLSach_SQL extends javax.swing.JFrame {

    /**
     * Creates new form QLSach_SQL
     */
    private int rowSelected = -1;
    
    SQLQuery query = new SQLQuery();
    
    /**
     * Creates new form QLSach_SQL
     */
    public QLSach_SQL() {
        initComponents();
        
        ShowTable();
        
        ResultSet rs = null;
        try {
            rs = query.GetBookCategoriese();
            cbTheLoai.removeAllItems();
            while (rs.next()) {
                cbTheLoai.addItem(rs.getString("TenLoai"));
            }           
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    public boolean isNumeric(String str) { 
        try {  
            Double.parseDouble(str);  
            return true;
        } catch(NumberFormatException e){  
            return false;  
        }  
    }
    
    private void ShowTable(){
        while (tbSach.getRowCount() > 0) {
            DefaultTableModel model = (DefaultTableModel)tbSach.getModel();
            model.removeRow(0);
        }
        
        ResultSet rs = null;
        
        try {
            DefaultTableModel model = (DefaultTableModel)tbSach.getModel();
            rs = query.GetBooks();
            while (rs.next()) {
                String number = rs.getString("GiaSach");
                double gia = Double.parseDouble(number);
                DecimalFormat format = new DecimalFormat("#,###");
                model.addRow(new Object[]{rs.getString("MaSach"), rs.getString("TenSach"), rs.getString("NamXB"), format.format(gia), rs.getString("TenLoai")});
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    private boolean LookingForBook (String code) {
        for(int i = 0 ; i < tbSach.getRowCount(); i += 1) {
            if (code.trim().equals(tbSach.getValueAt(i, 0).toString().trim())) {
                this.rowSelected = i;
                return true;
            }
        } 
        rowSelected = -1;
        return false;
    }
    
    private int CheckEmpty() {
        if (txtTenSach.getText().equals("") || txtGia.getText().equals("") || txtMaSach.getText().equals("") || txtNamXB.getText().equals("")) {
            return -1;
        } else if (txtMaSach.getText().length() != 6) {
            return -2;
        } else if (Integer.parseInt(txtNamXB.getText()) > 2021) {
            return -3;
        }
        return 1;
    }
    
    private void DeleteBook (int row) {
        ((DefaultTableModel)tbSach.getModel()).removeRow(row);
    }
    
    private void UpdateBook (String ma, String ten, String nam, String gia, String tl) throws SQLException{
        query.UpdateBook(ma, ten, gia, nam, tl);
        ShowTable();
    }
    
    private void AddNewBook(String ma, String ten, String nam, String gia, String tl){
        DefaultTableModel model = (DefaultTableModel)tbSach.getModel();
        double price = Double.parseDouble(gia);
        DecimalFormat formatter = new DecimalFormat("#,###");
        model.addRow(new Object[]{ma, ten, nam, formatter.format(price), tl});        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaSach = new javax.swing.JTextField();
        txtTenSach = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbTheLoai = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNamXB = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSach = new javax.swing.JTable();
        btnThoat = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("QUẢN LÝ THÔNG TIN SÁCH");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin sách", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setText("Mã sách");

        txtMaSach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaSachKeyReleased(evt);
            }
        });

        jLabel2.setText("Tên sách");

        jLabel3.setText("Giá bán");

        jLabel4.setText("Thẻ loại");

        cbTheLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.setEnabled(false);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.setEnabled(false);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel5.setText("Năm XB");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenSach)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaSach)
                            .addComponent(txtGia)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbTheLoai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNamXB))
                        .addGap(0, 138, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNamXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "Năm XB", "Giá", "Tên loại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbSach);
        if (tbSach.getColumnModel().getColumnCount() > 0) {
            tbSach.getColumnModel().getColumn(0).setResizable(false);
            tbSach.getColumnModel().getColumn(0).setPreferredWidth(35);
            tbSach.getColumnModel().getColumn(1).setResizable(false);
            tbSach.getColumnModel().getColumn(2).setResizable(false);
            tbSach.getColumnModel().getColumn(2).setPreferredWidth(35);
            tbSach.getColumnModel().getColumn(3).setResizable(false);
            tbSach.getColumnModel().getColumn(3).setPreferredWidth(30);
            tbSach.getColumnModel().getColumn(4).setResizable(false);
            tbSach.getColumnModel().getColumn(4).setPreferredWidth(45);
        }

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(291, 291, 291)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnThoat))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void tbSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSachMouseClicked
        // TODO add your handling code here:
        if (tbSach.getSelectedRow() >= 0) {
            btnXoa.setEnabled(true);
            btnSua.setEnabled(true);
            btnThem.setEnabled(false);
        } else {
            btnXoa.setEnabled(false);
            btnSua.setEnabled(false);
            btnThem.setEnabled(true);
        }

        int row = tbSach.getSelectedRow();
        String maSach = tbSach.getValueAt(row, 0).toString();
        String tenSach = tbSach.getValueAt(row, 1).toString();
        String namXB = tbSach.getValueAt(row, 2).toString();
        String gia = tbSach.getValueAt(row, 3).toString();
        String theLoai = tbSach.getValueAt(row, 4).toString();

        String newString = "";
        for(int i = 0; i < gia.length(); i+= 1) {
            if (gia.charAt(i) == ','){
                continue;
            }
            newString += gia.charAt(i);
        }
                
        txtMaSach.setText(maSach);
        txtTenSach.setText(tenSach);
        txtNamXB.setText(namXB);
        txtGia.setText(newString);
        cbTheLoai.setSelectedItem(theLoai);
    }//GEN-LAST:event_tbSachMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        String maSach = txtMaSach.getText();
        String tenSach = txtTenSach.getText();
        String gia = txtGia.getText();
        String namXB = txtNamXB.getText();
        String theLoai = cbTheLoai.getSelectedItem().toString();
        if (LookingForBook(maSach)) {
            if (CheckEmpty() > 0) {
                if (isNumeric(txtGia.getText()) && isNumeric(txtNamXB.getText())) {
                    int answer = JOptionPane.showConfirmDialog(this, "Cập nhật sách: " + tbSach.getValueAt(this.rowSelected, 1).toString(), "Cập nhật", JOptionPane.YES_NO_OPTION);
                    if (answer == JOptionPane.YES_OPTION) {
                        try {
                            UpdateBook(maSach, tenSach, namXB, gia, theLoai);
                        } catch (SQLException ex) {
                            Logger.getLogger(QLSach_SQL.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        JOptionPane.showMessageDialog(this, "Cập nhật sách thành công","Cập nhật", JOptionPane.INFORMATION_MESSAGE);
                    }                    
                } else {
                    JOptionPane.showMessageDialog(this, "Năm và giá là số mà sao nhập chữ vậy ???", "Lỗi nhập dữ liệu", JOptionPane.ERROR_MESSAGE);
                }
            } else if (CheckEmpty() == -1){
                JOptionPane.showMessageDialog(this, "Xin nhập đủ thông tin", "Lỗi nhập dữ liệu", JOptionPane.ERROR_MESSAGE);
            } else if (CheckEmpty() == -3) {
                JOptionPane.showMessageDialog(this, "Nhập năm xuất bản phải lớn hơn năm hiện tại", "Lỗi nhập dữ liệu", JOptionPane.ERROR_MESSAGE);
            } else if (CheckEmpty() == -2) {
                JOptionPane.showMessageDialog(this, "Mã sách phải có đúng 6 ký tự", "Lỗi nhập dữ liệu", JOptionPane.ERROR_MESSAGE);
            }
        } 
//        btnThem.setEnabled(false);
//        btnSua.setEnabled(true);
//        btnXoa.setEnabled(true);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtMaSachKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaSachKeyReleased
        // TODO add your handling code here:
         String maSach = this.txtMaSach.getText();
        if (LookingForBook(maSach)) {
            btnThem.setEnabled(false);
            btnSua.setEnabled(true);
            btnXoa.setEnabled(true);
            for(int i = 0 ; i < tbSach.getRowCount(); i += 1) {
                if (maSach.equals(tbSach.getValueAt(i, 0))) {
                    txtTenSach.setText(tbSach.getValueAt(i, 1).toString());
                    txtNamXB.setText(tbSach.getValueAt(i, 2).toString());
                    txtGia.setText(tbSach.getValueAt(i, 3).toString());
                    cbTheLoai.setSelectedItem(tbSach.getValueAt(i, 4));
                }
            }
        } else {
            btnThem.setEnabled(true);
            btnSua.setEnabled(false);
            btnXoa.setEnabled(false);
            txtTenSach.setText("");
            txtGia.setText("");
            txtNamXB.setText("");
            cbTheLoai.setSelectedIndex(0);
            tbSach.clearSelection();
        }
    }//GEN-LAST:event_txtMaSachKeyReleased

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int answer = JOptionPane.showConfirmDialog(this, "Xóa sách : " + tbSach.getValueAt(tbSach.getSelectedRow(), 1).toString(), "Xóa", JOptionPane.YES_NO_OPTION);
        if (answer == JOptionPane.YES_OPTION) {
            try {
                query.RemoveBook(txtMaSach.getText());            
                txtMaSach.setText("");
                txtTenSach.setText("");
                txtGia.setText("");
                txtNamXB.setText("");
                cbTheLoai.setSelectedIndex(0);
                ShowTable();
                JOptionPane.showMessageDialog(this, "Xóa thành công", "Xóa", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException e){
                e.printStackTrace();
            }            
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        String maSach = txtMaSach.getText();
        String tenSach = txtTenSach.getText();
        String gia = txtGia.getText();
        String nam = txtNamXB.getText();
        String tl = cbTheLoai.getSelectedItem().toString();        
        
        if (CheckEmpty() > 0) {
            if (isNumeric(txtGia.getText()) && isNumeric(txtNamXB.getText())) {
                int answer = JOptionPane.showConfirmDialog(this, "Thêm sách: " + txtTenSach.getText(), "Thêm sách", JOptionPane.YES_NO_OPTION);
                if (answer == JOptionPane.YES_OPTION) {                    
                    try {
                        AddNewBook(maSach, tenSach, nam, gia, tl);
                        query.AddBook(maSach, tenSach, gia, nam, tl);
                        String memory = maSach;
                        txtMaSach.setText("");
                        txtTenSach.setText("");
                        txtGia.setText("");
                        txtNamXB.setText("");
                    } catch (SQLException ex) {
                       Logger.getLogger(QLSach_SQL.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    JOptionPane.showMessageDialog(this, "Thêm sách thành công","Thêm sách", JOptionPane.INFORMATION_MESSAGE);
                }                
            } else {
                JOptionPane.showMessageDialog(this, "Năm và giá là số mà sao nhập chữ vậy ???", "Lỗi nhập dữ liệu", JOptionPane.ERROR_MESSAGE);
            }
        } else if (CheckEmpty() == -1){
            JOptionPane.showMessageDialog(this, "Xin nhập đủ thông tin", "Lỗi nhập dữ liệu", JOptionPane.ERROR_MESSAGE);
        } else if (CheckEmpty() == -3) {
            JOptionPane.showMessageDialog(this, "Nhập năm xuất bản phải lớn hơn năm hiện tại", "Lỗi nhập dữ liệu", JOptionPane.ERROR_MESSAGE);
        } else if (CheckEmpty() == -2) {
            JOptionPane.showMessageDialog(this, "Mã sách phải có đúng 6 ký tự", "Lỗi nhập dữ liệu", JOptionPane.ERROR_MESSAGE);
        }        
    }//GEN-LAST:event_btnThemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLSach_SQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLSach_SQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLSach_SQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLSach_SQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLSach_SQL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbTheLoai;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbSach;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtNamXB;
    private javax.swing.JTextField txtTenSach;
    // End of variables declaration//GEN-END:variables
}
